### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by withewolf78** [davidramiro/Marlin-Ai3M#104]
Hallo, ich habe das problem, mit dem mega x das mit dieser software der tisch nur noch nach vorne fährt und nicht mehr zurück.
danke für deine antwort.

**Comment by davidramiro** [comment]
The value `INVERT_Y_DIR` would have to be changed here: https://github.com/davidramiro/Marlin-Ai3M/blob/master/Marlin/Configuration.h#L855 and the firmware then recompiled according to these instructions: https://github.com/davidramiro/Marlin-AI3M/wiki/Customization-&-Compiling

In principle however this firmware does not support the Mega-X. As far as I know, it has a new display that is not backwards compatible.

If someone wants to make this change and can test it successfully on their Mega-X, please post feedback here. However, I am closing this issue because this firmware is only intended for the i3 Mega and Mega-S and therefore there is no bug in and of itself

--

Es müsste der Wert `INVERT_Y_DIR` hier umgestellt werden: https://github.com/davidramiro/Marlin-Ai3M/blob/master/Marlin/Configuration.h#L855 und die Firmware anschließend neu kompiliert werden, nach dieser Anleitung: https://github.com/davidramiro/Marlin-AI3M/wiki/Customization-&-Compiling

Prinzipiell unterstützt diese Firmware allerdings nicht den Mega-X. Soweit ich weiß hat dieser ein neues Display, welches nicht rückwärtskompatibel ist.

Falls jemand diese Änderung vornehmen möchte und es auf seinem Mega-X erfolgreich testen kann, gerne hier Rückmeldung geben. Ich schließe diese Issue aber dennoch, da diese Firmware nur für den i3 Mega und Mega-S gedacht ist und somit kein Bug im eigentlichen Sinne vorliegt.
