### ISSUE TITLE
Nozzle doesn't lift on pause [BUG]

### ISSUE THREAD

**Issue by MD3DDelta** [davidramiro/Marlin-AI3M#25]
the orginal pause  was , 10mm lift  and no retraction.

**Comment by davidramiro** [comment]
Confirmed, working on it on the dev branch.

https://github.com/davidramiro/Marlin-AI3M/tree/dev

Will update in a few days.

**Comment by MD3DDelta** [comment]
Wow , you are the best , thanks .

**Comment by davidramiro** [comment]
So far I reworked the handling of filament runout and pause here: https://github.com/davidramiro/Marlin-AI3M/commit/1fe1842a75ea57362bc6225d3ac3674300937dd5

For now, using pause raises the nozzle 10mm and retracts 7mm of filament.

I don't remember how the manufacturer firmware handles pause, could you please add that to the expected behaviour of the bug report template? (it's meant to be filled out so, see your first post and edit it accordingly please)

**Comment by MD3DDelta** [comment]
thanks david you are awesome , to prevent oozing , is very helpfull.
Ii  use the pause for unglog the nozzle , i have an few spools of old filament aand often they are bad pieces in them. every splool is dry and clean , just old about 5 years . 
How ca i support you with some money , you have defently earend it . 
paypal or wath else ?
thank you so much . 
when i end my upgrade on the mega i3 x-cariage i let you know . 
cheers mike

**Comment by davidramiro** [comment]
The latest release candidate can be found here:
https://kore.cc/i3mega/download/testing/pause/latest/

Has been tested a couple of times on two different machines, seems to work fine so far. Please check it out for yourself and report back.

And yes, I do have [PayPal](https://paypal.me/djusto/). A donation is not expected but of course always highly appreciated. 😀

**Comment by MD3DDelta** [comment]
it works , Just almost like the orginal .
Only 1 motor is winey, when it paused . i could't find out wich one . But the steppers stay cool , so is it a bit more power on .
i just send you 10 € , thank you for your work .
Regards Mike
