### ISSUE TITLE
[BUG] Screaming stepper motors with stock drivers

### ISSUE THREAD

**Issue by gitmacer** [davidramiro/Marlin-Ai3M#56]
**Describe the bug**
Always when the motors are powerd with this firmware they are screaming relativly loud to hold its position and while moving. As soon as I stop the motors the sound will disapear. For now I switched back to the stock firmware where the sound is a lot quieter till I know how to fix that.

**To Reproduce**
1. Start printer
2. Move axis by any value
3. hear error

**Expected behavior**
The same noise level as the stock firmware

**Printer (please complete the following information):**
 - Firmware version: [v1.4.6 stable]
 - Printing method [SD, USB (OctoPrint, Cura, ...)]
 - Model [i3 Mega]

**Comment by davidramiro** [comment]
For the stock drivers version of this firmware, the usual A4988 configuration is in use. Just like on Anycubics official (1.1.0) firmware. Hence this is not a specific issue of this particular firmware but more likely of Marlin 1.1.9 in general.

Anyways, I've never had anyone else report noisy stepper drivers when switching to this firmware so I have no idea what could be the issue here. Please head over to the official Marlin firmware repository and ask there.
